/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// GPIO memory structure definition
typedef struct
{
	volatile uint32_t MODER;	/* offset: 0x00	*/
	volatile uint32_t OTYPER;	/* offset: 0x04	*/
	volatile uint32_t OSPEEDR;	/* offset: 0x08 */
	volatile uint32_t PUPDR;	/* offset: 0x0C */
	volatile uint32_t IDR;		/* offset: 0x10 */
	volatile uint32_t ODR;		/* offset: 0x14 */
	volatile uint32_t BSRR;		/* offset: 0x18 */
	volatile uint32_t LCKR;		/* offset: 0x1C */
	volatile uint32_t AFRL;		/* offset: 0x20 */
	volatile uint32_t AFRH;		/* offset: 0x24 */
} GPIO_TypeDef;

// RCC memory structure definition
typedef struct
{
	volatile uint32_t DUMMY[12];
	volatile uint32_t AHB1ENR;	/* offset: 0x30 */
} RCC_TypeDef;

// Base Address Definitions
#define 	RCC_BASE 	0x40023800
#define		GPIOA_BASE	0X40020000

// Peripheral pointer definitions
#define RCC		((RCC_TypeDef*) RCC_BASE)
#define GPIOA	((GPIO_TypeDef*) GPIOA_BASE)

// 14: Bit mask for enabling GPIOIA (bit 0)
#define GPIOAEN			(1U << 0)
// 15: Bit mask for GPIOA pin 5
#define PIN5			(1U << 5)
// 16: Alias for PIN5 representing LED pin
#define LED_PIN			PIN5

int main(void)
{
	// Enable the clock access for GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	// Configure pin PA5 as output pin
	// set bit 10 as 1
	// set bit 11 as 0
	GPIOA->MODER |= (1U << 10);
	GPIOA->MODER &= ~(1U << 11);

	while (1) {
		// set output high for PA5
		// Using XOR operator to toggle off and on, and make it blink.
		GPIOA->ODR ^= LED_PIN;
		
		for (int i = 0; i < 2000000 ; i++) {
			;
		}
	}
}
