/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

// 14: Bit mask for enabling GPIOIA (bit 0)
#define GPIOAEN			(1U << 0)
// 15: Bit mask for GPIOA pin 5
#define PIN5			(1U << 5)
// 16: Alias for PIN5 representing LED pin
#define LED_PIN			PIN5

int main(void)
{
	// Enable the clock access for GPIOA
	RCC->AHB1ENR |= GPIOAEN;

	// Configure pin PA5 as output pin
	// set bit 10 as 1
	// set bit 11 as 0
	GPIOA->MODER |= (1U << 10);
	GPIOA->MODER &= ~(1U << 11);

	while (1) {
		// set output high for PA5
		// Using XOR operator to toggle off and on, and make it blink.
		GPIOA->ODR ^= LED_PIN;
		
		for (int i = 0; i < 2000000 ; i++) {
			;
		}
	}
}
