/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "systick.h"
#include "tim.h"
#include "uart.h"

void systick_demo();
void button_led_demo();
void tim_demo();
void uart_demo();

int main(void)
{
	uart_demo();
}

void uart_demo()
{
	// Initialization
	uart_init();
	while (1)
	{
		puts("Hello, world!\n");
		systick_msec_delay(300);
	}
}

void tim_demo(void)
{
	// Initialization
	led_init();
	tim2_1hz_init();

	while (1)
	{
		led_toggle();
		while (!(TIM2->SR & SR_UIF))
		{
		}

		TIM2->SR &= ~SR_UIF;
	}
}

void systick_demo(void)
{
	// Program initialization
	led_init();

	while (1)
	{
		led_toggle();
		systick_msec_delay(300);
	}
}

void button_led_demo(void)
{
	// Program initialization
	led_init();
	button_init();

	bool is_led_on = false;
	bool button_pressed;

	while (1)
	{
		// Get the button state
		button_pressed = get_button_state();

		if (button_pressed && !is_led_on)
		{
			led_on();
			is_led_on = true;
		}

		if (!button_pressed && is_led_on)
		{
			led_off();
			is_led_on = false;
		}

		systick_msec_delay(1);
	}
}
